{% set name = "harlequin-odbc" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/harlequin_odbc-{{ version }}.tar.gz
  sha256: beb2b57836ccdb21b4fa4b151e2cd6fc1b946f4f914eb233de5debc2c08920cf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.1,<4.0
    - harlequin >=1.9.1,<2.0.0
    - pyodbc >=5.0.0,<6.0.0

test:
  imports:
    - harlequin_odbc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tconbeer/harlequin-odbc
  summary: A Harlequin adapter for ODBC drivers.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/harlequin
